### ISSUE TITLE
GitChat: David Bray (CIO, FCC)

### ISSUE THREAD

**Issue by lukefretwell** [govfresh/gitchat#1]
Joining us for our GovFresh GitChat is David Bray, chief information officer, Federal Communications Commission.

![davidbray](https://cloud.githubusercontent.com/assets/1569463/2637082/f42306e6-be98-11e3-83cd-174ef18c819c.png)

How it works:
- Submit your questions using the 'Comment’ box.
- Chat date/time: April 7, 6:30-7:30 p.m. ET

What question(s) do you have for David?

**Comment by lukefretwell** [comment]
Would love to hear how you're able leverage social media the way you do (open, informal).

What process did you go through to get approval to leverage Twitter in that way?

What social media advice do you have for other c-level government executives?

**Comment by empower-your-coders** [comment]
Q1. What social media advice do you have for other c-level government executives? 

Pick a few channels to invest in, learn from, and monitor. You don't have to be everywhere (because your hours are limited) but you do have to be open to inputs and ideas from the public and other partner organizations. Social media is much more than "broadcast" -- it is being #open2ideas and #learning&listening from folks ... I find I learn a lot from hearing from the views of others, and then have a chance to also share some of the day-to-day challenges facing us in modernizing IT within an existing organization.

**Comment by lukefretwell** [comment]
Why do you think gov CIOs aren't more social?

**Comment by empower-your-coders** [comment]
Q2. What process did you go through to get approval to leverage Twitter in that way? 

I had to get legal and public affairs sign-off to use Twitter, which includes a clause that retweets are not necessarily an endorsement because in government we have to be careful about not giving endorsements. Demonstrating good judgment and sound choices in what I post and represent also helps.

**Comment by spjika** [comment]
How do you consider your responsibility to segment your official handle content and things you push out on your own channels? Are you heavily limiting what you personally post because if implicit connections to your role?

**Comment by empower-your-coders** [comment]
Q3: Why do you think gov CIOs aren't more social? 

Good question -- it might be a combination of concerns about ensuring the agency's message is consistent and uniform. There's also a lot of pressure right now on public service folks to not take too many risks, because there does seem to be an element that is quick to point out those who take risks and have them not always work out as planned. To that I point to the example of Admiral Chester W. Nimitz who early in his career as an Ensign ran the destroyer Decatur aground on a sand bar in the Philippines. The ship was pulled free the next day, and Nimitz was court-martialed, found guilty of neglect of duty, and issued a letter of reprimand.

http://en.wikipedia.org/wiki/Chester_W._Nimitz#Early_career

... that ended up assigning him to submarines, which became very relevant for WWI and WWII. He took a risk, made a mistake, learned from it, and moved on and eventually became a 5-star Admiral. 

Nowadays however, what would happen to a young Ensign who ran a U.S. boat aground in the world somewhere? Perhaps television coverage would probably be 48-72 hours on the topic, #FireNimitz might start trending on Twitter, and not only him, but perhaps his boss and his boss's boss might be called before Congress to explain what happened and be drummed out of the military. And the result? We would have lost a future 5-star Admiral. 

I also think there's a huge pressure on the time commitments for CIO. More of them might be more social if they felt like they had a supportive environment and that them taking the time to do it was valued by their agency leadership.

**Comment by empower-your-coders** [comment]
Q4. How do you consider your responsibility to segment your official handle content and things you push out on your own channels? Are you heavily limiting what you personally post because if implicit connections to your role? 

Great question @spjika – personally I feel like as a public servant, I have a responsibility to recognize I’m always serving the public and thus under the public view. The role of a public servant requires that we aspire to be available to the public and operate with (1) benevolence, (2) competence, and (3) integrity. 

I try to embody these three things wherever I go. What I do and say in-person is the same I would do and say online. 

As for content – I do think I have a responsibility to recognize that an in-person context conveys tone of voice, emotion, facial expressions, and eye contact. Online takes that a way so the opportunity for misunderstanding increases. 

Also if a question is asked that isn’t in my area of responsibility, I’ll defer and say I’m not the one who can best answer that question for you. Or if it is a case where someone on my team is the better expert than I, I’ll also defer to that individual – as I firmly believe any Agency leader should #empower-your-coders

**Comment by lukefretwell** [comment]
What's the hardest part of being a CIO for a federal agency?

**Comment by spjika** [comment]
Sounds fair. Given that, can we talk smack about @feomike on here? Californians are still a touch bitter that the FCC stole him.

**Comment by empower-your-coders** [comment]
Q5: Would love to hear how you're able leverage social media the way you do (open, informal). 

I'd like to first discuss the "why" then the "how": 

Why -- it's to be #open2ideas and learn from the public, partner organizations online. Also to celebrate some of the FCC #Rockstars who have accepted the noble mantle of public service and transforming IT at an existing government agency with an important mission that needs leading-edge IT. Props to folks like @awolfe76 and @japanlawprof and others at FCC. 

How -- through sharing status on some of our initiatives, sharing general news about the FCC, sharing some of the opportunities and challenges of being a CIO, and most importantly learning from others about their ideas and helping to integrate them into what we do here. Our goal is to have some of the best IT in government in 18 months or less @FCC starting from where we are at -- which includes a lot of 10+ year old legacy systems -- so that will only happen if we involve the public and partner orgs in the discussion and transformation. 

Q6: For @spjika re: @feomike 

Alas, we @FCC recently also had Mike stolen from us. He's gone to @CFPB (I was heartbroken) for a terrific new gig. I'm happy for him and it's great for @CFPB, and I also think he was looking for new challenges, however there's a hole where he was at @FCC so maybe we could convince @NIH to clone Mike for us all? 

Love @CFPB however they had the luxury of doing all their IT “new” about four years ago, not like @FCC which started in 1934 :-)

**Comment by lukefretwell** [comment]
Congratulations @feomike!

**Comment by spjika** [comment]
Wow, sorry to hear that. Related- how have you been able to cultivate a culture that is attractive to younger, more private sector oriented developer type folks- or is this a huge struggle at FCC also?

**Comment by empower-your-coders** [comment]
Q7: What's the hardest part of being a CIO for a federal agency? 

Hardest part is best embodied in Rudyard Kipling's poem "If-" which hangs outside my office door (my father gave me a copy of the poem when I was 20; that same copy has been in my wallet ever since including the response to 9/11, anthrax in 2001, travels to Afghanistan, and other interesting public service roles). 

The full poem is at: http://www.poetryfoundation.org/poem/175772 ... however the opening snippet captures the spirit: 

_If you can keep your head when all about you
    Are losing theirs and blaming it on you,
If you can trust yourself when all men doubt you,
    But make allowance for their doubting too;
If you can wait and not be tired by waiting,
    Or being lied about, don’t deal in lies,
Or being hated, don’t give way to hating,
    And yet don’t look too good, nor talk too wise:_

... Public service means public scrutiny, which is a good thing because we are here to serve the nation and the people. The challenge is we (as in "We The People") and our Founders, constructed the balance of power in our form of government so that there are intentional segments, checks-and-balances, compartments, and even turf battles between and within agencies as a way of preventing the rise of a king-like individual. The Founders after all had just fought a revolution against an oppressive government. The line from the Federalist Papers No. 51 reads: 

_Ambition must be made to counteract ambition... It may be a reflection on human nature, that such devices should be necessary to control the abuses of government. But what is government itself, but the greatest of all reflections on human nature?_

( from http://www.constitution.org/fed/federa51.htm )

So often times folks unfamiliar with the checks-and-balances and the intentional segments in government might look and say that's grossly inefficient or that's slow and bureaucratic, when in fact those checks-and-balances prevent what our Founders were worried about, which is the rise of a king-like individual. At the same time, 21st century IT requires us to work horizontality and across those compartments and turf. 

So being a CIO in the public sector requires you to be a "digital diplomat" internally and externally on these challenges and the need to change cultures plus reward mechanisms. It also requires you to be a "human flak jacket" as you work to address these challenges, work horizontally, change cultures, and reward mechanism. Sometimes being that flak jacket means taking metaphorical bullets from all angles.

**Comment by empower-your-coders** [comment]
Q8: Related- how have you been able to cultivate a culture that is attractive to younger, more private sector oriented developer type folks- or is this a huge struggle at FCC also? 

I'm happy for @feomike and it's of great benefit to @CFPB and our Nation that he's taking on another great challenge. Also, stay tuned, I think you'll hear some additional great news about him soon :-) 

Re: developer culture 

We are just now starting the FCC IT Transformation and yes -- as of the last two weeks have had on-board and start with us: 

(1) A #Rockstar detailee from the NIH to be our intrapreneur for the Office of the Chairman & Office the Management Director "intrapreneur" - Ms. Teresa Shea http://www.youtube.com/watch?v=OBpdsuLf0NU 

(2) A #Rockstar contractor to help with our internal and external strategy for the #Coordination&Communication of IT changes at the FCC - Ms. Sarah Millican www.linkedin.com/in/sarahantoinettemillican 

(3) A #Rockstar contractor from the Bay area to demonstrate a faster way of doing IT systems modernization and to help transform the systems we have at the FCC www.linkedin.com/in/professionalservices 

Now this is just a start, and we need more. I'm working on my end to ensure our HR processes are chugging as best and as fast as they can, and our Procurement processes are also chugging as best and as fast as they can. We've 18 months to do something great that's never been done before, so now is the time to make it happen. 

If there are altruistic, dedicated folks who want a reverse IPO = OPI = Opportunity for Positive Impact @FCC ... we're your place, and we're actively looking for great, proven #Rockstar talent to enable this transformation to happen.

**Comment by empower-your-coders** [comment]
The thing that inspires me daily is there is such important work to be done -- and now with the the internet we can work better across distances and time zones with the public, with partner organizations, and even within our own agency in ways that weren't possible 10 years ago or even 5 years ago. 

There are and have been several dedicated folks across @FCC working hard and late hours to make the Commission do great things. I often compare the days to being an “ultra-concentrated-protein-shake” there’s so much going on here that’s truly for the public, our partners, and to improve our world. 

@FCC We're actively pursuing mobile, we're modernizing our systems so that we can make more #opendata available for others. The FCC speed test app was #4 recently on the iOS store -- a first for any government -- http://www.fcc.gov/guides/mobile-speed-test-tip-sheet 

The National Broadband Map which deserves kudos to both @feomike and @xactoeric gets more than 5 million hits a month! http://www.broadbandmap.gov/ 

So there are great things that are now accelerating with our new Chairman at the FCC. "We The People" can make this transformation happen. It is the dedication and benevolence of folks in #PublicService that inspires me to get out of bed, be the underdog and demonstrate that @FCC can have some of the best IT in government.

**Comment by kinlane** [comment]
Hey if you guys are still chatting--I'm planning #APIStrat Chicago for end of September. Gonna announce soon. Looking to get about 1K people for 4th edition together. let me know if there any gov talks you'd like to see, conversations to be had!

**Comment by lukefretwell** [comment]
On the open data front, what are you currently doing and what are your plans are for moving that forward?

**Comment by empower-your-coders** [comment]
@kinlane terrific -- and yes, would be great to talk about how can #PublicService reuse consistent APIs for a "bottoms-up" approach to sharing of modular development across organizations as well as within organizations. We're starting that adventure here @FCC so that we don't build 100+ different ways of doing the same standard process (write from database to HTML5 for example) but instead begin to build a modular code library with API calls to the instance. Would love to have some of this be reusable with other public service orgs and have #opensource code they do also be reusable. 

The challenge then being how do we encourage consistent "bottoms-up APIs" without heavy top-down governance of them? #open2ideas

**Comment by empower-your-coders** [comment]
Q9: On the open data front, what are you currently doing and what are your plans are for moving that forward? 

Some of our data is already open, such as http://www.broadbandmap.gov/ or data from http://www.fcc.gov/guides/mobile-speed-test-tip-sheet 

Some of our data could be made more open in a better fashion, or in some cases a better draw. So as we modernize our systems, we will be planning and implementing both thin UIs as well as APIs to make the data more open to the public and partner organizations. The vision is the FCC is a trusted broker of data in and out appropriately, so that others can remix and analyze the data that we share in new ways. 

@GigiBSohnFCC is here and a great advocate for #opendata which I 100% support. Also part of our on-going strategy will be regular engagement with the public and our partners on what data would be most valuable for us to focus our energies first, and go from there. The FCC Chairman's Process Reform just sought public comment on elements of this and that will help inform what we focus on as top priorities: http://www.fcc.gov/document/fcc-seeks-public-comment-report-process-reform

**Comment by kinlane** [comment]
Definitely...we will have tracks on API design centric approaches using Swagger, RAML and API Blueprint....with a focus on re-use using via an API Commons model. So not just being design centric, but publishing your best patterns and allowing others to safely re-use, because these healthy patterns are publicly available and openly licensed. As well as discussion of open tooling around this.

We will also be having a talk on /api.json model which I'm working on derived from the open data - /data.json model using the API definition models outlined above. This will help in discovery and facilitate the re-use. 

Also we will be pushing on Hypermedia discussions which help in these areas. 

Great ideas-very relevant to what everyone is experiencing in space.

**Comment by empower-your-coders** [comment]
@kinlane Outstanding + you inspire me that we'll demonstrate it is possible for legacy #PublicService systems to be modernized, with scale, across large human endeavors. Here's the future ahead!

**Comment by kinlane** [comment]
Amen. Imagine when we can share the best examples of API patterns (budgets, facilities, calendars, images, etc.) as easily as we are sharing ideas here. We just need a language to do so, and that is what we are trying to create with API Blueprint, RAML and Swagger. We just need to encourage people to do so, and in an open forum.

**Comment by empower-your-coders** [comment]
With that, "We The People" can really become "We The People" who work hard, code hard, and collaborate to compose modular services that make-up a great network of #PublicService applications to improve our world. 

This: http://www.meetup.com/DC-Web-API-User-Group/ == should be happening across the nation and world.

**Comment by lukefretwell** [comment]
What's your take on how and when government should deploy open source options?

**Comment by empower-your-coders** [comment]
Q10: What's your take on how and when government should deploy open source options? 

In general, public service should use existing code -- ideally open source code -- if what the code provides fits their needs. 

If public service is developing code, I generally would like to recommend the code be open source unless there is sufficient legal or mission integrity reason to not make it so. That's part of a discussion later this year that @johnmscott is helping to organize -- can we encourage our procurement and legal folks to adopt a "default to open source first" posture and go from there?

**Comment by digiphile** [comment]
Hi @empower-your-coders Following up on @lukefretwell's question, could you share Web analytics from this page? 
http://fcc.gov/developer

I'm curious about:
*how much use those APIs receive monthly
*how that usage has changed over time
*The FCC's most popular data sets

2) How much interaction do the FCC data officers have with end users of their data sets? Will the FCC bring on a new chief data officer?
http://www.fcc.gov/data/officers

3) With respect to the National Broadband Map, how accurate is the data?

**Comment by empower-your-coders** [comment]
Greetings @digiphile: 

Q11-1.) I certainly can ask the team to share Web analytics for http://fcc.gov/developers ... some of the data you ask is not unfortunately readily available, so there may be a two-stage approach here. We can work to share what data we have readily available and work longer-term to make more available. There's a large research question embedded in "usage changed over time" that we may not have staff resources available to support :-) 

Q11-2.) After listening and learning from several folks @FCC, the FCC data officers were a working group that had atrophied in the last 12-14 months prior to my arrival. We're in the process of a re-invigorating of it. Part of it is connecting them with tools to make use of the data across the FCC -- part of it is simply making that data accessible across different systems. 

We don't have a solution in place to do that currently, instead we have 200+ different IT systems, 40% or more are 10 years older (… and that stat is from 2012! …), each with individual data schemas and models. So working with that data across the enterprise is a challenge. Investment in modernizing those systems or modern data tools has also be absent for a while -- however we hope to start fixing that this FY ideally with funding in FY15. Stay tuned to see if it arrives. 

It is also why you'll note the FCC Information and Data Officers are just that -- Information _and_ Data Officers, as separate tracks doesn't make a lot of sense since the data is _in_ information systems. Plus, since access to the data is tied to modernizing our legacy systems, you will see we have a FCC Chief Enterprise Architect -- a new position since my arrival -- since frankly the FCC was lacking an enterprise view to either its information systems or its data. 

The FCC Chief Enterprise Architect has a Lead for Enterprise Information and Data Integration which is serving as what you might call a CDO, however we opted to call this role that because it emphasizes what we need to do to get the data in a usable form: Enterprise Information and Data Integration. 

Right now any data requests beyond something that is pre-canned is very labor intensive here at the FCC, thus why your question might have to be two-stages, the first being what data we readily have available so I don't detract the limited team too much. The Enterprise Information and Data Integration already has a high-level plan to move to a (cloud-based) datamart for FCC where the data will be pulled from those 200+ legacy systems, indexed, and made available not only to folks at FCC, but also to the public and our partners via APIs and thin web-based UIs. That will help address #datascience @FCC and #opendata with the public. 

Q11-3.) With respect to the National Broadband Map, how accurate is the data? 

That's probably a better question for @xactoeric -- he and @feomike prior have poured their heart and soul into this. They're the experts. 

Hope this helps.

**Comment by lukefretwell** [comment]
Closing this GitChat out. 

Thank you @empower-your-coders for engaging in this new format!

Big shout to @spjika @kinlane @spjika for chiming in!

**Comment by empower-your-coders** [comment]
Additional questions from @digiphile: 

Q12-1.) On 18F -- I am watching the news reports and want to remain optimistic, however my observation is 18F has _not_ does a great job communicating to other government agencies what they're doing. In fact, it appears to have been fairly secretive, which seems curious and somewhat odd for an era of increased transparency and open endeavors? Maybe an approach that includes going to other agency CIOs and asked what the big issues you need fixed are, and having that dialogue with other #PublicService CIOs help inform the issues -- would be a great one? 

To be honest other agency CIOs & I have commented that we hear more about 18F from outside news reporting than inside the public sector itself -- that may need to be fixed? :-) Also, naming your endeavor after your street address seems curious in an age where the internet means great #PublicService does not need to be location-based seems puzzling? 

Frankly across #PublicService, IT procurement needs to be fixed in making it leaner and easier for agencies to do -- and that is something squarely in GSA's wheelhouse. There is the GSA Schedule and Bulk Purchasing Agreements, and expanding that will help agencies do IT faster. Have more startups on the GSA Schedule. GSA itself a service agency that works with other mission-focused parts of #PublicService and so I worry when relevancy "at the edge" of a mission is abstracted or pulled away. My focus, learned from several years of #PublicService experience, has been more on empowering the edge. 

Let me give the example of the FCC website and how it might relate to 18F. Back in 2010, prior to my arrival, folks have told me that the FCC.gov website design was taken away from the Bureaus and Offices -- and from the IT shop too -- and instead was done in a centralized approach that did not engage the partners that use the website nor the FCC Bureaus and Offices that know what the partners need. Very little end-user inputs or acceptance testing. The result was a website that had been winning awards prior to 2010 to one that didn't. That's what I worry about when relevancy "at the edge" of a mission is abstracted or pulled away. 

Q12-2.) On the topic of IT procurement as I think it is much more important: 

Rumors that the FCC previously before my arrival moved to the cloud are vastly overstated. After listening and learning from folks, I discovered our website for the most part is still hosted here. Attempts to procure an iOS developer’s “cloud” license results in our current Procurement shop (outside of IT) saying that it cannot be done on a govt credit card, but instead must be done as a purchase order because the current terms specify automatic renewal which is counter to the Anti-deficiency Act http://en.wikipedia.org/wiki/Antideficiency_Act 

Also doing a $60 trial license for cloud device = the same. So we're having to work closely to work to improve these areas. FedRamp and GSA schedule only gets you so far, there's more work that needs to be done on the side of procurement that would make our lives a lot easier. 

The good news is FCC has been doing agile and lean since my arrival. We've had at least 4 different FCC-wide training sessions on agile, through our IT contractors to both IT staff and programmatic stewards (the folks who the mission-centric systems are being built for) on agile, as the process needs to involve them in tandem, working together. Another reason why I believe you can't abstract too much from the programmatic stewards and succeed with IT. It's why I'm encouraging Intrapreneurs -- entrepreneurs on the inside -- at FCC. 

Q12-3.) Lastly, if I was to urge where to place attention and energy, it would be on educating Procurement shops -- and the General Counsels of agencies that provide legal guidance on what can and cannot be procured -- as to what's possible. If you want people to take risks, be lean, be agile, and do great stuff taking these steps to #empower-the-edge and #empower-your-coders are great first steps! 

Hope this helps.

**Comment by empower-your-coders** [comment]
Let me also thank @lukefretwell for moderating this great discussion -- it's been a great last 3 hours of wonderful questions and comments from the public. Onwards and upwards together!   :-)

**Comment by lukefretwell** [comment]
Thank you, David!

**Comment by dcloud** [comment]
I'll just add these for people who want to know things about [18f](https://18f.gsa.gov/):

http://18fblog.tumblr.com/post/80066867648/hello-world-we-are-18f

https://github.com/18F

**Comment by empower-your-coders** [comment]
@dcloud -- those are good links and have been tracking them, I really wish however 18F would (1) do more to ask #PublicService agencies what do we need and what are our most urgent priorities, and (2) then drill down to specifics about what they're doing to address them. I'm all for lean and agile, and we're also running a "startup in government" @FCC too. 

What I'd enjoy is understanding more how GSA can listen, learn, and incorporate common hot priorities across the #PublicSector into what it develops? Hope this helps.
