### ISSUE TITLE
How do you define 'civic startup?'

### ISSUE THREAD

**Issue by lukefretwell** [govfresh/gitchat#2]
The term 'civic startup' is being used more and more lately, so much that it's lost its original meaning, which was about eliminating high-costs of IT products and, especially, eliminating vendor lock-in.

As we watch the civic technology industry mature, it appears that more and more companies that claim to be 'civic startups' are really just offering new products to government without a (relatively) easy discontinue option. 

The de-emphasis on open source solutions is particularly noticeable.

I'm curious, how do you define 'civic startup?'

**Comment by empower-your-coders** [comment]
If Public Service = what we choose to do together that we can't do alone. 

And Civic Institutions are Public Service Institutions 

Than I suggest that a "civic startup" is a new cooperative venture, perhaps with trusted actors on our behalf, to accomplish that which we choose to do together as a society, as a nation, or as a world, that we can't do alone. 

It could be a completely new effort, or a transformational new effort within an existing legacy organization. 

#two_cents
</two_cents>

**Comment by lukefretwell** [comment]
Posting these links for reference per Twitter convo with @digiphile (cc @opennorth @mySociety @mheadd):
- https://www.globalintegrity.org/posts/the-sharing-economy-is-not-civic-tech/
- http://civic.io/2012/01/10/what-does-a-civic-startup-look-like/
- http://www.mysociety.org/2013/08/05/what-should-we-do-about-the-naming-deficitsurplus-part-2/
- http://blog.opennorth.ca/2013/11/21/the-civic-power-sector/

**Comment by roughani** [comment]
I'm going to take a more traditional view on this topic. First, let's begin with _startup_. I think a noncontroversial definition of a startup comes from Steve Blank who says that **a startup is a temporary organization in search of a scalable and repeatable business model**. That is, a startup needs to generate revenue. It can be for-profit, non-profit, B-corp, etc. But the activity of a startup needs to eventually lead to financial sustainability if it's going to succeed in having impact on the world.

@mheadd does a good job of [capturing the civic nature of the definition](http://civic.io/2012/01/10/what-does-a-civic-startup-look-like/) without getting into whether a civic startup necessarily needs to deploy open source products. While there are many good reasons to go open source, there are a lot of good reasons not to. @andrewhoppin makes [a good case for OpenSaaS](http://opensource.com/government/14/1/opensaas-and-government-innovation), but he makes his case with the public interest in mind. And that's why I began with the definition of a startup. If you're an entrepreneur, you already have so many things going against you, you need to prioritize mitigating risk. 

Unless and until public agencies craft procurement policies that award preference points to open source vendors, I don't believe that the public benefit of deploying open source products outweighs the risk of competitors eating your lunch. At the end of the day, we all want to drive toward greater, **sustainable** impact. And I think Omidyar Network's Stacy Donohue [articulately frames this challenge](http://www.ssireview.org/blog/entry/fostering_for_profit_civic_innovation) in the context of encouraging civic startups to be for-profit rather than non-profit:

> Sustainability is crucial to meeting the demands of civic challenges. Philanthropy is critical to fostering civic innovation and government transparency. But it is also limited by a relatively fixed pool of foundations and high-net-worth individuals committed to the cause.

Believe me, I'm no advocate for vendor lock-in and love seeing incumbents get disrupted. However, when you're starting a company and you need to pay your bills, you have to minimize risk. If we want to enjoy the benefits of open source, we need the marketplace to reward that approach. In other words, we need to get to a point where open source is a strategy for reducing risk not only from the perspective of government, but also from the perspective of the entrepreneurs who are the ones creating civic startups with nothing more than sweat equity. 

Also see @mojombo's [Open Source (Almost) Everything](http://tom.preston-werner.com/2011/11/22/open-source-everything.html).

**Comment by planspark** [comment]
A civic startup is one whose primary aim is to address issues of public concern.

**Comment by lukefretwell** [comment]
@roughani Great points. Makes me wonder if 'civic startup' has evolved into a meaningless term (similar to 'green'). If it's just as much about minimizing risks for the entrepreneur as it is about creating a sustainable IT solution for government, it's not much different than what traditional IT vendors have been offering for decades.

**Comment by fccdbray** [comment]
@roughani & @lukefretwell -- maybe we're focusing too much on procurement and services? Perhaps a civic startup is less about the technology and more about the business of doing **civic activities** (i.e., what we choose to do together that we can't do alone). 

If so, civic startup attempts new models to accomplish that which we choose to do together as a society, as a nation, or as a world, that we can't do alone. Example: representative democracy at the birth of the United States, in an era when the prevalent paradigm was monarchy 1.0 ? 

Thoughts?

**Comment by roughani** [comment]
@lukefretwell @empower-your-coders I think we should distinguish between civic innovation and civic startups. And perhaps it's the innovation piece that captures what we're all striving for: new, fresh, and exciting approaches to solving public problems; that can be done inside government, outside government, or in the space between; and, led by people regardless of their official status/position. 

To me, however, once you're a startup, your number one priority is to survive the [Valley of Death](http://www.forbes.com/sites/martinzwilling/2013/02/18/10-ways-for-startups-to-survive-the-valley-of-death/) and at that point, civic innovation may need to take a back seat (depending on what your customers want). I would much rather be a non-profit civic startup (or a startup within gov, hello @18F!) than a for-profit one.
