### ISSUE TITLE
GitChat: Gavin Newsom (Lt. Gov, Calif.)

### ISSUE THREAD

**Issue by lukefretwell** [govfresh/gitchat#4]
### About GitChat

[GitChat](https://github.com/govfresh/gitchat) is an open, informal chat with leading civic innovators using GitHub as a platform for engagement.
### Featured guest

**Gavin Newsom**
Lieutenant Governor, [California](http://www.ltg.ca.gov/)
Author, [Citizenville](http://www.amazon.com/Citizenville-Square-Digital-Reinvent-Government/dp/1594204721/ref=tmm_hrd_title_0)
Twitter: [@gavinnewsom](@gavinnewsom)

![gavinnewsom](https://cloud.githubusercontent.com/assets/1569463/2892765/cd0c5bfc-d540-11e3-8507-1ef11780e4d1.png)
### How it works
- Submit questions using the 'Comment’ box.
- Gavin will reply during the designated times
### Chat date/time
- May 6-7 (noon-noon PT)

**Comment by lukefretwell** [comment]
Thank you for agreeing to do this, Gavin. Always breaking new ground.

I'll kick it off with 3 softballs. ;-)
- What can government do to encourage more economic opportunities for startups and new businesses?
- What's the status of California's open data strategy and what do we need to do to get it back on track?
- One of the big challenges the state has is attracting IT talent to work for government, especially given the Silicon Valley alternatives. Thoughts on how to address this issue for California as well as other governments? What can government do to attract IT talent?

**Comment by patrickcrossan** [comment]
Are you concerned the budget proposal to cap IHSS hours to 40 per week will force recipients into nursing homes and effectively kill the IHSS program? Are you exploring other options such as cash for care?

**Comment by NACinSAC** [comment]
Thank You for Citizenville. Do you Believe that there "must be a way" to get MORE Citizens Involved in local Gov't meetings even FOR  those that are Bedbound/HouseBound that are wanting to Participate online and watch ? Current system is Very Frustrating and limiting. Can't we use 21st Cent. Tech "to Be Inclusive" ? Bedridden doesn't mean Braindead or not worthy or we don't pay taxes. Thanks for caring. ❤

**Comment by roughani** [comment]
There's an emerging civic tech + innovation scene popping up at the local and regional level in Sacramento. At the same time, however, there are "Two Sacramentos" (a Sacramento for the people who are rooted here and building startups to solve local/regional problems vs. a Sacramento for the state government and enterprise IT crowd). In other words, there's a total disconnect between state and local government when it comes to open data and open government. If we're going to achieve a government as a platform reality, we need to all be having the same conversation.

How can those of us working locally make ourselves more relevant and push the conversation around civic innovation and the state-local relationship forward?

**Comment by frenchmark** [comment]
What is your opinion onSenator Correa's bill SB1262?

**Comment by heirofjesus** [comment]
Mr. Lt. Governor,

First off, I want to say thank you. I genuinely believe you are one of the few lawmakers left in this country that actually may be working for the people of this country and state. Whenever you run for President, I can't wait to be involved with helping you win!

A few questions:
1. How do you think that the decisions of Buckley v Valeo has affected Congressional politics over the last 50 years or so, and how can we move forward with Campaign Finance Reform?
2. California is always seems said to be at the forefront of businesses not being able to take care of themselves in the long run in our state, how can we move forward and adjust our tax codes in order to encourage (especially small business) to come back to California, and stay here?
3. Do you have any suggestions or ideas on how to root out the seemingly Cold War chess game we are currently playing with Russia while trying to help Ukraine.
4. Colorado Supreme Court ruled in favor 2-1 to stand behind US Federal Law, and fire a gentlemen by the name Brandon Coats for marijuana use in a state where it is not only legal, but he was using it with a medical prescription. 

How do you think this plays out in the fight between states and federal government wrestling for control over this issue? 

Thank you for your time,

-Saahil Malik & the people of California

**Comment by meganesque** [comment]
Hi Gavin - 

I am thrilled to see California taking the lead with "open policy making" using the California probate laws as their test case via Mike Gatto's wiki-bill.  I am wondering what your role was in promoting this idea, and whether you will get involved in taking it to the next level, i.e., with other issues and with additional and more relevant/impactful changes to the probate laws?  

With Thomas Piketty's "Capital in the 21st Century" a best selling phenomenon in the US, this seems like an excellent time to drill down into what I feel is the core issue in the US, or the growing wealth/income gap.  

There are many ways to close the gap in addition to Piketty's proposed wealth tax.  Here is a link to my OGP blog post that addresses this issue at the global level: https://www.linkedin.com/today/post/article/20140403151313-4966-42-voices-about-open-government-continuous-improvement?trk=mp-reader-card 

Here is the link to my post about Mike Gatto's wiki-bill that addresses it at the state level: https://www.linkedin.com/today/post/article/20140404110315-4966-coming-soon-small-things-that-make-a-big-difference?trk=mp-reader-card

Thank you and keep up the good OpenGov work!

Megan

**Comment by GavinNewsom** [comment]
Thanks for having me @lukefretwell, glad to be a part of this! Sorry for the delay. I will do my best to answer as many questions as I can. I'll start with the questions you provided.

Question: What can government do to encourage more economic opportunities for startups and new businesses?

In many ways, one of the government's most important functions in aiding start-ups is to help connect the dots for new ventures.  There already exists networks of organizations, both public and private, whose sole purpose is to spur economic development.  Economic development corporations exist in every county and region, the iHub network is being built out and expanded to encourage tech innovation, and countless accelerators and incubators have popped up around the state.  The Governor's Office of Business and Economic Development (GO-Biz) is now a one-stop shop for everything business, including permits and licenses.  But one area where government could help even more is the directing of capital to new small businesses.  Access to capital is a refrain I often hear from business owners as I travel the state.  Our state government could work harder and smarter to incentivize investment in start-ups.  Whether through streamlining and promoting specialized grants and loans, expanding the infrastructure bank, or creating a new Green Bank, California needs to step in and bet big on our entrepreneurs.  

I’d also mention that I enthusiastically support the growth of crowdfunding. Both in-kind and direct financial resources because it’s not just about money, it’s about providing mentorship, pro-bono services, office space and help putting together a business plan that enable businesses grow. By supporting more incubators and shared spaces and organizations like Tumml, which I just visited yesterday, and others like it, an environment to thrive is created.

**Comment by GavinNewsom** [comment]
@meganesque thanks for your question

Question: I am thrilled to see California taking the lead with "open policy making" using the California probate laws as their test case via Mike Gatto's wiki-bill. I am wondering what your role was in promoting this idea, and whether you will get involved in taking it to the next level, i.e., with other issues and with additional and more relevant/impactful changes to the probate laws?

Assemblyman Gatto’s bill to use crowdsourcing as a way to craft legislation is just what I talk about in my book, Citizenville. This approach is engaging and allowing government officials to not just do things for citizens but do things with citizens. I applaud him and am very support of his efforts to take this approach to involve citizens in crafting legislation that matters to them. There is so much opportunity to grow and I hope probate laws are only the beginning, I hope we will begin to see many other areas addresses.

**Comment by GavinNewsom** [comment]
@patrickcrossan in regards to your Question: Are you concerned the budget proposal to cap IHSS hours to 40 per week will force recipients into nursing homes and effectively kill the IHSS program? Are you exploring other options such as cash for care?

As Mayor of San Francisco we raised the bar for IHSS and I was proud to be among its strongest supporters and I continue to be to this day, so yes I am concerned about this proposal and its impact. I have expressed my strong support to members of the legislature and others. 

We have an aging population and we have a moral, ethical and economic responsibility to allow them a place to live in dignity. It’s a great investment to the future and our state.

**Comment by GavinNewsom** [comment]
@lukefretwell another answer to a question you posed: One of the big challenges the state has is attracting IT talent to work for government, especially given the Silicon Valley alternatives. Thoughts on how to address this issue for California as well as other governments? What can/is government do/doing to attract IT talent?

I have two thoughts on this. On the one hand we are competing with some of the savviest and most dynamic companies anywhere in the world right here in Silicon Valley for talent. On the other hand, you’d be surprised at the quality of some our own IT staff we already have in government. What we need to do, however, is allow them to work. We need to give them the freedom to express themselves on their own terms in their work place. Allow them to unleash their entrepreneurial energy and not be trapped in this old way of thinking and see what happens, I bet some remarkable things could come from it. 

Most importantly we need to lead, and we need to create energy and enthusiasm, to encourage like minded-IT professionals to serve in government and not just the private sector.

**Comment by GavinNewsom** [comment]
@NACinSAC your question
Thank You for Citizenville. Do you Believe that there "must be a way" to get MORE Citizens Involved in local Gov't meetings even FOR those that are Bedbound/HouseBound that are wanting to Participate online and watch ? Current system is Very Frustrating and limiting. Can't we use 21st Cent. Tech "to Be Inclusive" ? Bedridden doesn't mean Braindead or not worthy or we don't pay taxes. Thanks for caring. ❤

I appreciate the comments about the book. As you know it’s the very argument I make in Citizenville. Meeting people where they are and creating conditions where people can be active citizens so that everyone has the capacity to be fully participatory is something we absolutely have to encourage. Active citizenship is not just physically showing up to a town hall meeting, it’s making citizen’s co-producers, rather than government petitioning you. It’s making you a part of government and creating a two-way conversation with elected officials.

**Comment by GavinNewsom** [comment]
Question: There's an emerging civic tech + innovation scene popping up at the local and regional level in Sacramento. At the same time, however, there are "Two Sacramentos" (a Sacramento for the people who are rooted here and building startups to solve local/regional problems vs. a Sacramento for the state government and enterprise IT crowd). In other words, there's a total disconnect between state and local government when it comes to open data and open government. If we're going to achieve a government as a platform reality, we need to all be having the same conversation. How can those of us working locally make ourselves more relevant and push the conversation around civic innovation and the state-local relationship forward?

I completely agree with premise of this question @roughani . You are right, there is a lot of civic innovation happening locally and not so much at the state level. I always say remarkable things are happening at the local levels. If you don’t like what you’re seeing up top, flip the pyramid. There is a lot of excitement, optimism and innovation happening in cities around California and our nation. Don’t wait for around for state and federal government to make these changes; it’s local that will lead the way. I continue to be enthusiastic about organizations like Code for America that are embedding these values into cities and hopefully more state and federal organizations across the country.

**Comment by GavinNewsom** [comment]
@lukefretwell your last question

What's the status of California's open data strategy and what do we need to do to get it back on track?

California does not have much of an open data policy. We’re not even debating it as we should. 

While I was mayor of San Francisco, we required machine-readable, downloadable open data and it cost us nothing. All these private sector companies started to pop up because we decided to take information that was captured in the vaults of government and just put some simple data sets online in each city department and make them available. 

What did that take? Nothing, a simple executive order followed up by legislation. The governor should do the same thing. We should put the resources back into that data portal we have and get serious here.

A growing number of cities and states across the country are doing similar things and California is behind the curve.

**Comment by GavinNewsom** [comment]
@heirofjesus thank you for posing all of your questions

Questions: How do you think that the decisions of Buckley v Valeo has affected Congressional politics over the last 50 years or so, and how can we move forward with Campaign Finance Reform?

I think the Supreme Courts decision in the 1970s affected a lot of what you have seen in politics since and what you see today. Money talks. I’ve always been a supporter of campaign finance reform, more disclosure and some form form of public finance. 

Question: California is always seems said to be at the forefront of businesses not being able to take care of themselves in the long run in our state, how can we move forward and adjust our tax codes in order to encourage (especially small business) to come back to California, and stay here?

California’s got an entrepreneurial spirit running through its veins. We still remain the dominant innovation center in all of America and we are adept at inspiring startups as well as, or better than, any other location. We are vulnerable, however, in supporting and scaling growth of mid-size and large companies. That vulnerability was underscored by Toyota’s recent announcement to move its headquarters to Texas, as well as other high profile businesses that have left our state. That said, I don’t believe in a race to the bottom. California will never be the cheapest place to do business, but we can be the best. While it’s important to encourage business to relocate into our state, I would argue it’s much more important to support organic growth within our state. We need to not only have a recruitment strategy but also a retention strategy.

Question: Do you have any suggestions or ideas on how to root out the seemingly Cold War chess game we are currently playing with Russia while trying to help Ukraine.

There’s an old African proverb that says if you want to go fast go alone, if you want to go far go together. We have to speak with one voice. The European Union, led by Chancellor Merkel and the U.S. must speak with one voice and I commend the President for his efforts to do just that. While sanctions can be frustrating at first, I believe we are seeing some signs as recently as today that they may be having an impact. It’s critical that the President and our European allies maintain a willingness to substantially increase sanctions against sectors of the Russian economy as necessary as events unfold.

Question: Colorado Supreme Court ruled in favor 2-1 to stand behind US Federal Law, and fire a gentlemen by the name Brandon Coats for marijuana use in a state where it is not only legal, but he was using it with a medical prescription.

How do you think this plays out in the fight between states and federal government wrestling for control over this issue?

I don’t know enough about the details of this case and look forward to learning more. But I strongly support the taxation and regulation of marijuana and am leading a working group in California to put it on the ballot in 2016. The war on drugs has been a complete failure. It’s cost the United States a trillion dollars and counting. It’s time we take a serious look at a ways to safely and effectively implement legalization of marijuana, but still maintain the health and well being of our communities.

**Comment by GavinNewsom** [comment]
Thank you all for your questions, I apologize again for the delay in getting responses. This is a great new way for government to engage with citizens. Fun to help break new ground. I hope to participate in a GitChat again soon.

**Comment by patrickcrossan** [comment]
Thank you for your time and attention to our questions. 

----- Original Message -----

**Comment by lukefretwell** [comment]
@GavinNewsom Thank you for taking the time to do this. Really appreciate. Hopefully, we'll see you again here soon. :-)
